[package]
name = "rust_container_runner"
version = "0.0.0"
edition = "2021"
publish = false

[[bin]]
name = "eth_rpc"

[[bin]]
name = "tcp"

[dependencies]
clarity = { git = "https://github.com/onomyprotocol/clarity.git", rev = "4c866defe098304cdb418d907ba407f2cdbab543" }
futures = "0.3"
lazy_static = "1"
tokio = { version = "1.17", features = ["macros", "rt-multi-thread"] }
u64_array_bigints = { version = "0.3", default-features = false, features = ["serde_support"] }
#web30 = { path = "../web30" }
#web30 = { git = "https://github.com/onomyprotocol/web30.git", rev = "645c0509246fedff01aed1aa4c26eb804f3fec1a" }
web30 = { git = "https://github.com/AaronKutch/web30.git", rev = "c493f590894f7dde186d3fae06bae4664a740165" }
