[package]
name = "rust_container_runner"
version = "0.0.0"
edition = "2021"
publish = false

[[bin]]
name = "eth_rpc"

[[bin]]
name = "tcp"

[dependencies]
clarity = { git = "https://github.com/onomyprotocol/clarity.git", rev = "3e875b608a2d9302c8b23dd40dc8705901db230c" }
futures = "0.3"
lazy_static = "1"
tokio = { version = "1.17", features = ["macros", "rt-multi-thread"] }
u64_array_bigints = { version = "0.3", default-features = false, features = ["serde_support"] }
#web30 = { path = "../web30" }
#web30 = { path = "../web30", features = ["debug_errors", "debug_requests", "debug_responses"] }
#web30 = { git = "https://github.com/AaronKutch/web30.git", rev = "19e3ac9f95c8b8b1ac0f4bae020a3598d3158c87" }
web30 = { git = "https://github.com/AaronKutch/web30.git", rev = "19e3ac9f95c8b8b1ac0f4bae020a3598d3158c87", features = ["debug_errors", "debug_requests", "debug_responses"] }
