[package]
name = "rust_container_runner"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
web30 = { path = "../web30" }
#web30 = { git = "https://github.com/onomyprotocol/web30.git", rev = "645c0509246fedff01aed1aa4c26eb804f3fec1a" }
#web30 = { git = "https://github.com/AaronKutch/web30.git", rev = "8407c6da5f4fcee6e49c20460732cd00d50de846" }
tokio = { version = "1.17", features = ["macros", "rt-multi-thread"] }
clarity = { git = "https://github.com/onomyprotocol/clarity.git", rev = "52bc13f7d2778d293e2d787528d481604620a281" }
lazy_static = "1"
futures = "0.3"
u64_array_bigints = { version = "0.3", default-features = false, features = ["serde_support"] }
