[package]
name = "rust_container_runner"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
web30 = { git = "https://github.com/onomyprotocol/web30.git", rev = "909950b43faa014ebfdced5074b59179e35fb65a", features = []}
#web30 = { path = "../web30" }
tokio = { version = "1.17", features = ["macros", "rt-multi-thread"] }
clarity = { git = "https://github.com/onomyprotocol/clarity.git", rev = "3e875b608a2d9302c8b23dd40dc8705901db230c" }
lazy_static = "1"
futures = "0.3"
u64_array_bigints = { version = "0.3", default-features = false, features = ["serde_support"] }
rand = "0.8"
