[package]
name = "rust_container_runner"
version = "0.0.0"
edition = "2021"
publish = false

[[bin]]
name = "eth_rpc"

[[bin]]
name = "tcp"

[dependencies]
#web30 = { git = "https://github.com/onomyprotocol/web30.git", rev = "7f379993a3d5f331fd8e8e0a0770186f0fbc9860" }
web30 = { path = "../web30" }
tokio = { version = "1.17", features = ["macros", "rt-multi-thread"] }
clarity = { git = "https://github.com/onomyprotocol/clarity.git", rev = "4c866defe098304cdb418d907ba407f2cdbab543" }
lazy_static = "1"
futures = "0.3"
u64_array_bigints = { version = "0.3", default-features = false, features = ["serde_support"] }

#[patch.crates-io]
#u64_array_bigints = { git = "https://github.com/AaronKutch/u64_array_bigints.git", rev = "107ba324b6c48cad3b186f1e1ce8b919308248a6" }
