version: "3"

networks:
  net:
    external: true

services:
  test:
    container_name: test
    build:
      context: .
      dockerfile: dockerfile
    hostname: test
    networks:
      - net
    entrypoint: [ "bash", "/run_eth_rpc.sh" ]
