version: "3"

networks:
  testnet:
    external: true

services:
  proxy_program_loader:
    container_name: proxy_program_loader
    image: neonlabsorg/evm_loader:ci-proxy-caller-program
    environment:
      - SOLANA_URL=http://host_solana:8899
    networks:
      - testnet
    command: bash -c "deploy-proxy_program.sh"

  postgres:
    container_name: postgres
    image: ${DB_IMAGE}
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: neon-db
      POSTGRES_USER: neon-proxy
      POSTGRES_PASSWORD: neon-proxy-pass
    hostname: postgres
    healthcheck:
      test: [ CMD-SHELL, "pg_isready -h postgres -p 5432" ]
      interval: 3s
      timeout: 3s
      retries: 10
      #start_period: 5s
    expose:
      - "5432"
    ports:
      - "5432"
    networks:
      - testnet

  #dbcreation:
  #  container_name: dbcreation
  #  image: ${PROXY_IMAGE}
  #  environment:
  #    SOLANA_URL: http://host_solana:8899
  #    POSTGRES_HOST: localhost
  #    POSTGRES_DB: neon-db
  #    POSTGRES_USER: neon-proxy
  #    POSTGRES_PASSWORD: neon-proxy-pass
  #  entrypoint: /bin/sh
  #  command: proxy/run-dbcreation.sh
  #  networks:
  #    - testnet
  #  depends_on:
  #    postgres:
  #      condition: service_healthy

  proxy:
    container_name: proxy
    image: ${PROXY_IMAGE}
    environment:
      SOLANA_URL: http://host_solana:8899
      FAUCET_URL: http://faucet:3333
      POSTGRES_DB: neon-db
      POSTGRES_USER: neon-proxy
      POSTGRES_PASSWORD: neon-proxy-pass
      LOG_NEON_CLI_DEBUG: "YES"
      FUZZING_BLOCKHASH: "YES"
      CONFIG: ci
      #PP_SOLANA_URL: ${CI_PP_SOLANA_URL:-https://api.devnet.solana.com}
      PYTH_MAPPING_ACCOUNT: ${CI_PYTH_MAPPING_ACCOUNT:-BmA9Z6FjioHJPpjT39QazZyhDRUdZy2ezwx4GiDdE2u2}
      MIN_OPERATOR_BALANCE_TO_WARN: 4565760000 # = 913152000 * 5 (5 storage accounts) = 4.56576 SOL
      MIN_OPERATOR_BALANCE_TO_ERR: 913152000 # = solana rent 131072 (= Rent-exempt minimum: 0.913152 SOL) SOLs to create a storage
      MINIMAL_GAS_PRICE: 1
      ENABLE_PRIVATE_API: "YES"
      ALLOW_UNDERPRICED_TX_WITHOUT_CHAINID: "YES"
      LOG_FULL_OBJECT_INFO: "YES"
      EVM_LOADER: 53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io
    hostname: proxy
    depends_on:
      dbcreation:
        condition: service_completed_successfully
    ports:
      - 9090:9090
    expose:
      - "8888"
      - "9090"
    networks:
      - testnet
    entrypoint: proxy/run-test-proxy.sh
    healthcheck:
      test: [ CMD-SHELL, "/opt/health_check_proxy.sh" ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s

  deploy_contracts:
    container_name: deploy_contracts
    image: ${EVM_LOADER_IMAGE}
    environment:
      - SOLANA_URL=http://host_solana:8899
      - SPL_TOKEN_AUTHORITY=/opt/contracts/ci-tokens/owner-keypair.json
    networks:
      - testnet
    depends_on:
      proxy:
        condition: service_healthy
    command: bash -c "create-test-accounts.sh 1 && deploy-contracts.sh"

  faucet:
    container_name: faucet
    image: ${FAUCET_IMAGE}
    environment:
      FAUCET_RPC_BIND: 0.0.0.0
      FAUCET_RPC_PORT: 3333
      FAUCET_RPC_ALLOWED_ORIGINS: '["http://airdropper"]'
      FAUCET_WEB3_ENABLE: 'true'
      WEB3_RPC_URL: http://host_solana:8899
      WEB3_PRIVATE_KEY: 0x4deacb079b4714c38f39508aa8900039f2721ed8686835d43347ba9267da767b
      NEON_ERC20_TOKENS: '["0xB521b9F3484deF53545F276F1DAA50ef0Ca82E2d", "0x8a2a66CA0E5D491A001957edD45A6350bC76D708", "0x914782059DC42d4E590aeFCfdbF004B2EcBB9fAA", "0x7A7510b9b18241C788a7aAE8299D1fA6010D8128"]'
      NEON_ERC20_MAX_AMOUNT: 1000
      FAUCET_SOLANA_ENABLE: 'true'
      SOLANA_URL: http://host_solana:8899
      NEON_OPERATOR_KEYFILE: /root/.config/solana/id.json
      NEON_ETH_MAX_AMOUNT: 50000
      TEST_FAUCET_INIT_NEON_BALANCE: 100000000
      EVM_LOADER: 53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io
      NEON_TOKEN_MINT: HPsV9Deocecw3GeZv1FkAPNCBRfuVyfw9MMwjwRe1xaU
      NEON_TOKEN_MINT_DECIMALS: 9
      SOLANA_COMMITMENT: confirmed
    hostname: faucet
    ports:
      - 3333:3333
    expose:
      - "3333"
    networks:
      - testnet
    entrypoint: ./run-test-faucet.sh
    depends_on:
      deploy_contracts:
        condition: service_completed_successfully

  airdropper:
    container_name: airdropper
    image: ${PROXY_IMAGE}
    environment:
      POSTGRES_DB: neon-db
      POSTGRES_USER: neon-proxy
      POSTGRES_PASSWORD: neon-proxy-pass
      POSTGRES_HOST: postgres
      SOLANA_URL: http://host_solana:8899
      FAUCET_URL: http://faucet:3333
      NEON_CLI_TIMEOUT: 0.9
      INDEXER_ERC20_WRAPPER_WHITELIST: ANY
      PRICE_UPDATE_INTERVAL: 10
      START_SLOT: LATEST
      #PP_SOLANA_URL: ${PP_SOLANA_URL:-https://api.devnet.solana.com}
      PYTH_MAPPING_ACCOUNT: ${CI_PYTH_MAPPING_ACCOUNT:-BmA9Z6FjioHJPpjT39QazZyhDRUdZy2ezwx4GiDdE2u2}
      MAX_CONFIDENCE_INTERVAL: 0.01
    hostname: airdropper
    entrypoint: ./run-airdropper.sh
    networks:
      - testnet
    depends_on:
      dbcreation:
        condition: service_completed_successfully
      faucet:
        condition: service_started

  indexer:
    container_name: indexer
    image: ${PROXY_IMAGE}
    environment:
      SOLANA_URL: http://host_solana:8899
      POSTGRES_DB: neon-db
      POSTGRES_USER: neon-proxy
      POSTGRES_PASSWORD: neon-proxy-pass
      GATHER_STATISTICS: "YES"
      LOG_FULL_OBJECT_INFO: "YES"
      CONFIG: ci
      EVM_LOADER: 53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io
    hostname: indexer
    depends_on:
      dbcreation:
        condition: service_completed_successfully
    expose:
      - "8887"
    networks:
      - testnet
    entrypoint: proxy/run-indexer.sh
