version: "3"

networks:
  net:
    external: true

services:
  solana:
    container_name: solana
    image: neonlabsorg/evm_loader:${NEON_EVM_COMMIT}
    environment:
      - RUST_LOG=solana_runtime::system_instruction_processor=trace,solana_runtime::message_processor=debug,solana_bpf_loader=debug,solana_rbpf=debug
      - SOLANA_URL=http://localhost:8899
    hostname: solana
    entrypoint:
      /opt/solana/bin/solana-run-neon.sh
    healthcheck:
      # Must be available from outside (calling without -u causes premature result)
      test: [ CMD-SHELL, "./wait-for-neon.sh" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s

  proxy:
    container_name: proxy
    image: neonlabsorg/proxy:${REVISION}
    environment:
      - SOLANA_URL=http://solana:8899
    hostname: proxy
    depends_on:
      solana:
        condition: service_healthy
    networks:
      - net
    healthcheck:
      test: [ CMD-SHELL, "/opt/health_check_proxy.sh" ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s